include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    todo: ignore
    invalid_annotation_target: ignore
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart]

linter:
  rules:
    public_member_api_docs: false # TODO: enable this rule after project is nearly complete
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
