name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  ios:

    name: Build iOS
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest ]

    steps:

      # Set up Flutter.
      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.x'

      # checkout codebase.
      - name: Checkout codebase
        uses: actions/checkout@v3

      # Get packages.
      - name: Get dependencies
        run: flutter pub get

      # Build ios app
      - name: Build app
        run: |
          flutter build ipa \
          --no-codesign \
          --export-method app-store \
          --null-assertions \
          --split-debug-info=build/app/outputs/symbols --obfuscate

  aos:

    name: Build AOS
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest ]

    steps:

      # Set up Java.
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Set up Flutter.
      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.x'

      # checkout codebase.
      - name: Checkout codebase
        uses: actions/checkout@v3

      # Get packages.
      - name: Get dependencies
        run: flutter pub get

      - name: Build appbundle
        run: |
          flutter build appbundle \
          --deferred-components \
          --validate-deferred-components \
          --null-assertions \
          --no-track-widget-creation \
          --split-debug-info=build/app/outputs/symbols \
          --obfuscate
